/**
 * @file user-types.ts
 * @description
 * Contains interfaces related to user profile or user identity data
 * beyond the ephemeral ConnectionState from chat-types.
 *
 * Key Exports:
 * - UserProfile: Minimal user data for the global scoreboard or chat
 *
 * @notes
 * - This can be expanded if we integrate real user management in the future.
 */

/**
 * Represents a user's profile within the plugin.
 * This is distinct from ephemeral connection states used by PartyKit.
 */
export interface UserProfile {
  /**
   * Unique identifier for the user.
   * Could be generated by an auth system or random ID.
   */
  userId: string;

  /**
   * The user's chosen display name.
   */
  nickname: string;

  /**
   * Optional field describing the user's current task or status.
   */
  currentTask?: string;

  /**
   * A flag indicating if the user is shadow-banned from chat.
   * Possibly set by the moderation system.
   */
  shadowBanned?: boolean;
}
